[package]
name = "bevy_atari"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

native = [
  "bevy/bevy_wgpu",
]

web = [
  "bevy_webgl2"
]

[dependencies]
bevy = {git = "https://github.com/bevyengine/bevy", default-features=false}
bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2", optional=true}
winit = {version = "0.23.0", features = ["web-sys", "x11"], default-features = false}
w65c02s = "0.9.2"

[patch.'https://github.com/bevyengine/bevy']
bevy = {path = "../bevy", default-features=false}

[profile.dev.package."*"]
opt-level = 2
debug = false
debug-assertions = false
overflow-checks = false
incremental = true
codegen-units = 16

[profile.dev]
opt-level = 2
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false

# [profile.release.package."*"]
# codegen-units = 1
# opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
# opt-level = 's'
